---
mappings:
- alias: "ri.foundry.main.dataset.0542d418-99cd-4273-8484-1df7a87c7e60"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0542d418-99cd-4273-8484-1df7a87c7e60"
- alias: "ri.foundry.main.dataset.11c69551-93e4-4fd4-ba03-f4f70f6564c2"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.11c69551-93e4-4fd4-ba03-f4f70f6564c2"
- alias: "ri.foundry.main.dataset.189cbacb-e1b1-4ba8-8bee-9d6ee805f498"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.189cbacb-e1b1-4ba8-8bee-9d6ee805f498"
- alias: "ri.foundry.main.dataset.1976f164-0085-40a9-a76b-17a1522374bb"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.1976f164-0085-40a9-a76b-17a1522374bb"
- alias: "ri.foundry.main.dataset.27e2f3c0-eab2-42a9-a49e-0e9505314c71"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.27e2f3c0-eab2-42a9-a49e-0e9505314c71"
- alias: "ri.foundry.main.dataset.37ecdae3-a272-4fbc-91ca-537d4c4583c7"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.37ecdae3-a272-4fbc-91ca-537d4c4583c7"
- alias: "ri.foundry.main.dataset.3a128a4e-49cb-4ac9-95f8-c6cfd0da2b62"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3a128a4e-49cb-4ac9-95f8-c6cfd0da2b62"
- alias: "ri.foundry.main.dataset.3c73987b-4bdd-4bac-92a4-4e0a89081f06"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3c73987b-4bdd-4bac-92a4-4e0a89081f06"
- alias: "ri.foundry.main.dataset.4d057f59-6e10-44bf-b8e3-99f6008eb2d8"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4d057f59-6e10-44bf-b8e3-99f6008eb2d8"
- alias: "ri.foundry.main.dataset.5601bd47-740e-452b-877f-a0bd86b7a733"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5601bd47-740e-452b-877f-a0bd86b7a733"
- alias: "ri.foundry.main.dataset.5be41d98-9869-4dea-8533-729364278b33"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5be41d98-9869-4dea-8533-729364278b33"
- alias: "ri.foundry.main.dataset.5e29af40-69a9-4c34-a56f-d2fb0e66c0b5"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5e29af40-69a9-4c34-a56f-d2fb0e66c0b5"
- alias: "ri.foundry.main.dataset.65d92ade-9983-47f9-8707-294d50ea6b44"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.65d92ade-9983-47f9-8707-294d50ea6b44"
- alias: "ri.foundry.main.dataset.66e4c3a3-1628-461b-9caf-c9d084cab6fd"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.66e4c3a3-1628-461b-9caf-c9d084cab6fd"
- alias: "ri.foundry.main.dataset.67ad0ae4-ef14-4b48-b1a0-9c70ab346ee2"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.67ad0ae4-ef14-4b48-b1a0-9c70ab346ee2"
- alias: "ri.foundry.main.dataset.68112dd8-5929-439d-8a94-1c428e1f47f0"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.68112dd8-5929-439d-8a94-1c428e1f47f0"
- alias: "ri.foundry.main.dataset.7372e2b4-742e-440b-8aa9-8b8007ad85f3"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7372e2b4-742e-440b-8aa9-8b8007ad85f3"
- alias: "ri.foundry.main.dataset.74d75bae-54a7-482c-9c5d-049512c9595d"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.74d75bae-54a7-482c-9c5d-049512c9595d"
- alias: "ri.foundry.main.dataset.79a84d6a-90b9-4cdd-8ddc-84acec6203ba"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.79a84d6a-90b9-4cdd-8ddc-84acec6203ba"
- alias: "ri.foundry.main.dataset.7af51406-aeab-4f20-817b-f3eaaed6c442"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7af51406-aeab-4f20-817b-f3eaaed6c442"
- alias: "ri.foundry.main.dataset.7b6351c3-7ad4-478e-bc58-b96f6a86419d"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7b6351c3-7ad4-478e-bc58-b96f6a86419d"
- alias: "ri.foundry.main.dataset.7e056689-d3f3-477a-99ed-2829628ea25f"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7e056689-d3f3-477a-99ed-2829628ea25f"
- alias: "ri.foundry.main.dataset.80d75a82-aa6c-4db5-a433-117bc75e29ac"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.80d75a82-aa6c-4db5-a433-117bc75e29ac"
- alias: "ri.foundry.main.dataset.8181188a-2fc9-4987-9097-2ffc58a0eba7"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8181188a-2fc9-4987-9097-2ffc58a0eba7"
- alias: "ri.foundry.main.dataset.849acac0-002a-4f66-becf-93b138c285d3"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.849acac0-002a-4f66-becf-93b138c285d3"
- alias: "ri.foundry.main.dataset.8535c293-b3d3-45b4-8513-9c4a47fb65fe"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8535c293-b3d3-45b4-8513-9c4a47fb65fe"
- alias: "ri.foundry.main.dataset.86b5d04c-6b39-4361-9aba-88b257fe8317"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.86b5d04c-6b39-4361-9aba-88b257fe8317"
- alias: "ri.foundry.main.dataset.8968763f-4429-4fcf-9a97-d1da5194f4da"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8968763f-4429-4fcf-9a97-d1da5194f4da"
- alias: "ri.foundry.main.dataset.91e727e3-c12b-4b8f-bc4d-df58f03152a5"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.91e727e3-c12b-4b8f-bc4d-df58f03152a5"
- alias: "ri.foundry.main.dataset.9b1b80c9-1a9d-43a5-8cfc-6f96441f4a00"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9b1b80c9-1a9d-43a5-8cfc-6f96441f4a00"
- alias: "ri.foundry.main.dataset.a20ce57a-cc5a-4366-b022-0270b8556b2a"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a20ce57a-cc5a-4366-b022-0270b8556b2a"
- alias: "ri.foundry.main.dataset.a8373a3c-8242-41c9-a05c-a84a49e69eb7"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a8373a3c-8242-41c9-a05c-a84a49e69eb7"
- alias: "ri.foundry.main.dataset.aa54a011-57e2-4f33-ae43-58672b01c39e"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.aa54a011-57e2-4f33-ae43-58672b01c39e"
- alias: "ri.foundry.main.dataset.af70446b-de8d-4c0c-ba2f-951a7df8166d"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.af70446b-de8d-4c0c-ba2f-951a7df8166d"
- alias: "ri.foundry.main.dataset.b24dcc91-b53c-40be-824d-18b6251ded26"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b24dcc91-b53c-40be-824d-18b6251ded26"
- alias: "ri.foundry.main.dataset.b3ca45aa-26bd-4f6a-8d66-b2a587045095"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b3ca45aa-26bd-4f6a-8d66-b2a587045095"
- alias: "ri.foundry.main.dataset.ba7b0876-47e8-4639-ac77-c9bc874e36ce"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ba7b0876-47e8-4639-ac77-c9bc874e36ce"
- alias: "ri.foundry.main.dataset.c291e468-0835-4504-82d1-074cb4a3288a"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c291e468-0835-4504-82d1-074cb4a3288a"
- alias: "ri.foundry.main.dataset.d57577ad-45c3-4112-a9d1-8113b8694b04"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d57577ad-45c3-4112-a9d1-8113b8694b04"
- alias: "ri.foundry.main.dataset.d9e42f28-bc60-4d21-ab03-d8cf20084e3a"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d9e42f28-bc60-4d21-ab03-d8cf20084e3a"
- alias: "ri.foundry.main.dataset.dd27b45d-d6ef-48b0-b557-2fadd918e1f5"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dd27b45d-d6ef-48b0-b557-2fadd918e1f5"
- alias: "ri.foundry.main.dataset.dd790a04-08a9-4041-96d8-034c21d5ca73"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dd790a04-08a9-4041-96d8-034c21d5ca73"
- alias: "ri.foundry.main.dataset.e1cb9a58-6c56-4a67-9a65-54eab1c84553"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e1cb9a58-6c56-4a67-9a65-54eab1c84553"
- alias: "ri.foundry.main.dataset.e30d14b7-2e40-44e5-8a81-ba223bb2ea0a"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e30d14b7-2e40-44e5-8a81-ba223bb2ea0a"
- alias: "ri.foundry.main.dataset.e9bfc4a2-4919-4b4b-9f30-edc760fc8acc"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e9bfc4a2-4919-4b4b-9f30-edc760fc8acc"
- alias: "ri.foundry.main.dataset.ec596e6f-be23-4959-8ea8-f22cd935afdb"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ec596e6f-be23-4959-8ea8-f22cd935afdb"
- alias: "ri.foundry.main.dataset.fc596324-4b10-4552-8bc4-815be83c0695"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.fc596324-4b10-4552-8bc4-815be83c0695"
- alias: "ri.foundry.main.dataset.fc73f974-baad-4c10-b64d-aed01877a226"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.fc73f974-baad-4c10-b64d-aed01877a226"
